// Home utility data — generated by tools/parse_data.js (see README). Do not hand-edit.
window.UTILITY_DATA = {
  "generated": "2026-07-13",
  "location": "Salt Lake City, UT",
  "water": [
    {
      "month": "2021-12",
      "periodStart": "2021-12-02",
      "periodEnd": "2022-01-04",
      "cubicFeet": 700,
      "cost": 97.2,
      "breakdown": {
        "water": 25.01,
        "sewer": 28.65,
        "sanitation": 26.25,
        "stormWater": 9.34,
        "streetLight": 4.17,
        "franchiseFee": 3.78
      }
    },
    {
      "month": "2022-01",
      "periodStart": "2022-01-05",
      "periodEnd": "2022-02-01",
      "cubicFeet": 500,
      "cost": 78.86,
      "breakdown": {
        "water": 19.47,
        "sewer": 23.6,
        "sanitation": 21.62,
        "stormWater": 7.69,
        "streetLight": 3.43,
        "franchiseFee": 3.05
      }
    },
    {
      "month": "2022-02",
      "periodStart": "2022-02-02",
      "periodEnd": "2022-03-01",
      "cubicFeet": 700,
      "cost": 81.99,
      "breakdown": {
        "water": 22.43,
        "sewer": 23.6,
        "sanitation": 21.62,
        "stormWater": 7.69,
        "streetLight": 3.43,
        "franchiseFee": 3.22
      }
    },
    {
      "month": "2022-03",
      "periodStart": "2022-03-02",
      "periodEnd": "2022-04-01",
      "cubicFeet": 500,
      "cost": 86.46,
      "breakdown": {
        "water": 20.76,
        "sewer": 26.12,
        "sanitation": 23.94,
        "stormWater": 8.52,
        "streetLight": 3.8,
        "franchiseFee": 3.32
      }
    },
    {
      "month": "2022-04",
      "periodStart": "2022-04-02",
      "periodEnd": "2022-05-02",
      "cubicFeet": 1800,
      "cost": 111.34,
      "breakdown": {
        "water": 44.23,
        "sewer": 26.12,
        "sanitation": 23.94,
        "stormWater": 8.52,
        "streetLight": 3.8,
        "franchiseFee": 4.73
      }
    },
    {
      "month": "2022-05",
      "periodStart": "2022-05-03",
      "periodEnd": "2022-06-01",
      "cubicFeet": 1200,
      "cost": 96.12,
      "breakdown": {
        "water": 31.84,
        "sewer": 25.28,
        "sanitation": 23.16,
        "stormWater": 8.24,
        "streetLight": 3.68,
        "franchiseFee": 3.92
      }
    },
    {
      "month": "2022-06",
      "periodStart": "2022-06-02",
      "periodEnd": "2022-07-01",
      "cubicFeet": 6500,
      "cost": 241.49,
      "breakdown": {
        "water": 168.49,
        "sewer": 25.6,
        "sanitation": 23.28,
        "stormWater": 8.29,
        "streetLight": 3.68,
        "franchiseFee": 12.15
      }
    },
    {
      "month": "2022-07",
      "periodStart": "2022-07-02",
      "periodEnd": "2022-08-01",
      "cubicFeet": 7000,
      "cost": 301.35,
      "breakdown": {
        "water": 208.92,
        "sewer": 36.05,
        "sanitation": 27.5,
        "stormWater": 9.79,
        "streetLight": 3.8,
        "franchiseFee": 15.29
      }
    },
    {
      "month": "2022-08",
      "periodStart": "2022-08-02",
      "periodEnd": "2022-09-01",
      "cubicFeet": 6100,
      "cost": 268.56,
      "breakdown": {
        "water": 177.99,
        "sewer": 36.05,
        "sanitation": 27.5,
        "stormWater": 9.79,
        "streetLight": 3.8,
        "franchiseFee": 13.43
      }
    },
    {
      "month": "2022-09",
      "periodStart": "2022-09-02",
      "periodEnd": "2022-10-03",
      "cubicFeet": 3600,
      "cost": 185.17,
      "breakdown": {
        "water": 96.89,
        "sewer": 37.22,
        "sanitation": 28.39,
        "stormWater": 10.1,
        "streetLight": 3.92,
        "franchiseFee": 8.65
      }
    },
    {
      "month": "2022-10",
      "periodStart": "2022-10-04",
      "periodEnd": "2022-11-01",
      "cubicFeet": 1300,
      "cost": 115.41,
      "breakdown": {
        "water": 38.36,
        "sewer": 33.73,
        "sanitation": 25.73,
        "stormWater": 9.16,
        "streetLight": 3.55,
        "franchiseFee": 4.88
      }
    },
    {
      "month": "2022-11",
      "periodStart": "2022-11-02",
      "periodEnd": "2022-12-01",
      "cubicFeet": 400,
      "cost": 100.28,
      "breakdown": {
        "water": 21.67,
        "sewer": 34.89,
        "sanitation": 26.61,
        "stormWater": 9.47,
        "streetLight": 3.68,
        "franchiseFee": 3.96
      }
    },
    {
      "month": "2022-12",
      "periodStart": "2022-12-02",
      "periodEnd": "2023-01-03",
      "cubicFeet": 600,
      "cost": 113.19,
      "breakdown": {
        "water": 26.56,
        "sewer": 38.38,
        "sanitation": 29.27,
        "stormWater": 10.42,
        "streetLight": 4.04,
        "franchiseFee": 4.52
      }
    },
    {
      "month": "2023-01",
      "periodStart": "2023-01-04",
      "periodEnd": "2023-02-01",
      "cubicFeet": 400,
      "cost": 97.19,
      "breakdown": {
        "water": 21.18,
        "sewer": 33.73,
        "sanitation": 25.73,
        "stormWater": 9.16,
        "streetLight": 3.55,
        "franchiseFee": 3.84
      }
    },
    {
      "month": "2023-02",
      "periodStart": "2023-02-02",
      "periodEnd": "2023-03-01",
      "cubicFeet": 500,
      "cost": 95.89,
      "breakdown": {
        "water": 22.38,
        "sewer": 32.57,
        "sanitation": 24.84,
        "stormWater": 8.84,
        "streetLight": 3.43,
        "franchiseFee": 3.83
      }
    },
    {
      "month": "2023-03",
      "periodStart": "2023-03-02",
      "periodEnd": "2023-04-03",
      "cubicFeet": 800,
      "cost": 116.8,
      "breakdown": {
        "water": 29.96,
        "sewer": 38.38,
        "sanitation": 29.27,
        "stormWater": 10.42,
        "streetLight": 4.04,
        "franchiseFee": 4.73
      }
    },
    {
      "month": "2023-04",
      "periodStart": "2023-04-04",
      "periodEnd": "2023-05-01",
      "cubicFeet": 700,
      "cost": 99.49,
      "breakdown": {
        "water": 25.78,
        "sewer": 32.57,
        "sanitation": 24.84,
        "stormWater": 8.84,
        "streetLight": 3.43,
        "franchiseFee": 4.03
      }
    },
    {
      "month": "2023-05",
      "periodStart": "2023-05-02",
      "periodEnd": "2023-06-01",
      "cubicFeet": 2400,
      "cost": 148.51,
      "breakdown": {
        "water": 64.74,
        "sewer": 36.05,
        "sanitation": 27.5,
        "stormWater": 9.79,
        "streetLight": 3.8,
        "franchiseFee": 6.63
      }
    },
    {
      "month": "2023-06",
      "periodStart": "2023-06-02",
      "periodEnd": "2023-07-03",
      "cubicFeet": 6500,
      "cost": 289.91,
      "breakdown": {
        "water": 196.08,
        "sewer": 36.41,
        "sanitation": 28.71,
        "stormWater": 10.2,
        "streetLight": 3.95,
        "franchiseFee": 14.56
      }
    },
    {
      "month": "2023-07",
      "periodStart": "2023-07-04",
      "periodEnd": "2023-08-01",
      "cubicFeet": 6800,
      "cost": 359.62,
      "breakdown": {
        "water": 272.48,
        "sewer": 25.88,
        "sanitation": 28.77,
        "stormWater": 10.07,
        "streetLight": 3.91,
        "franchiseFee": 18.51
      }
    },
    {
      "month": "2023-08",
      "periodStart": "2023-08-02",
      "periodEnd": "2023-09-01",
      "cubicFeet": 6000,
      "cost": 314.98,
      "breakdown": {
        "water": 225.76,
        "sewer": 27.66,
        "sanitation": 30.76,
        "stormWater": 10.77,
        "streetLight": 4.18,
        "franchiseFee": 15.85
      }
    },
    {
      "month": "2023-09",
      "periodStart": "2023-09-02",
      "periodEnd": "2023-10-02",
      "cubicFeet": 3700,
      "cost": 206.25,
      "breakdown": {
        "water": 123.18,
        "sewer": 27.66,
        "sanitation": 30.76,
        "stormWater": 10.77,
        "streetLight": 4.18,
        "franchiseFee": 9.7
      }
    },
    {
      "month": "2023-10",
      "periodStart": "2023-10-03",
      "periodEnd": "2023-11-01",
      "cubicFeet": 400,
      "cost": 100.36,
      "breakdown": {
        "water": 25.59,
        "sewer": 26.77,
        "sanitation": 29.77,
        "stormWater": 10.42,
        "streetLight": 4.04,
        "franchiseFee": 3.77
      }
    },
    {
      "month": "2023-11",
      "periodStart": "2023-11-02",
      "periodEnd": "2023-12-04",
      "cubicFeet": 400,
      "cost": 109.55,
      "breakdown": {
        "water": 27.35,
        "sewer": 29.45,
        "sanitation": 32.74,
        "stormWater": 11.46,
        "streetLight": 4.45,
        "franchiseFee": 4.1
      }
    },
    {
      "month": "2023-12",
      "periodStart": "2023-12-05",
      "periodEnd": "2024-01-02",
      "cubicFeet": 600,
      "cost": 101.56,
      "breakdown": {
        "water": 29.03,
        "sewer": 25.88,
        "sanitation": 28.77,
        "stormWater": 10.07,
        "streetLight": 3.91,
        "franchiseFee": 3.9
      }
    },
    {
      "month": "2024-01",
      "periodStart": "2024-01-03",
      "periodEnd": "2024-02-02",
      "cubicFeet": 500,
      "cost": 105.56,
      "breakdown": {
        "water": 28.19,
        "sewer": 27.66,
        "sanitation": 30.76,
        "stormWater": 10.77,
        "streetLight": 4.18,
        "franchiseFee": 4
      }
    },
    {
      "month": "2024-02",
      "periodStart": "2024-02-03",
      "periodEnd": "2024-03-06",
      "cubicFeet": 400,
      "cost": 109.55,
      "breakdown": {
        "water": 27.35,
        "sewer": 29.45,
        "sanitation": 32.74,
        "stormWater": 11.46,
        "streetLight": 4.45,
        "franchiseFee": 4.1
      }
    },
    {
      "month": "2024-03",
      "periodStart": "2024-03-07",
      "periodEnd": "2024-04-01",
      "cubicFeet": 600,
      "cost": 92.37,
      "breakdown": {
        "water": 27.27,
        "sewer": 23.2,
        "sanitation": 25.8,
        "stormWater": 9.03,
        "streetLight": 3.5,
        "franchiseFee": 3.57
      }
    },
    {
      "month": "2024-04",
      "periodStart": "2024-04-02",
      "periodEnd": "2024-05-01",
      "cubicFeet": 1400,
      "cost": 124.86,
      "breakdown": {
        "water": 48.71,
        "sewer": 26.77,
        "sanitation": 29.77,
        "stormWater": 10.42,
        "streetLight": 4.04,
        "franchiseFee": 5.15
      }
    },
    {
      "month": "2024-05",
      "periodStart": "2024-05-02",
      "periodEnd": "2024-06-01",
      "cubicFeet": 900,
      "cost": 114.08,
      "breakdown": {
        "water": 36.23,
        "sewer": 27.66,
        "sanitation": 30.76,
        "stormWater": 10.77,
        "streetLight": 4.18,
        "franchiseFee": 4.48
      }
    },
    {
      "month": "2024-06",
      "periodStart": "2024-06-02",
      "periodEnd": "2024-07-01",
      "cubicFeet": 6600,
      "cost": 391.6,
      "breakdown": {
        "water": 278.96,
        "sewer": 48.02,
        "sanitation": 29.86,
        "stormWater": 10.45,
        "streetLight": 4.06,
        "franchiseFee": 20.25
      }
    },
    {
      "month": "2024-07",
      "periodStart": "2024-07-02",
      "periodEnd": "2024-08-01",
      "cubicFeet": 7200,
      "cost": 406.34,
      "breakdown": {
        "water": 285.29,
        "sewer": 49.97,
        "sanitation": 33.81,
        "stormWater": 11.85,
        "streetLight": 4.59,
        "franchiseFee": 20.83
      }
    },
    {
      "month": "2024-08",
      "periodStart": "2024-08-02",
      "periodEnd": "2024-09-01",
      "cubicFeet": 5600,
      "cost": 336.23,
      "breakdown": {
        "water": 219.15,
        "sewer": 49.97,
        "sanitation": 33.81,
        "stormWater": 11.85,
        "streetLight": 4.59,
        "franchiseFee": 16.86
      }
    },
    {
      "month": "2024-09",
      "periodStart": "2024-09-02",
      "periodEnd": "2024-10-01",
      "cubicFeet": 3400,
      "cost": 242.25,
      "breakdown": {
        "water": 132.97,
        "sewer": 49.04,
        "sanitation": 32.72,
        "stormWater": 11.46,
        "streetLight": 4.45,
        "franchiseFee": 11.61
      }
    },
    {
      "month": "2024-10",
      "periodStart": "2024-10-02",
      "periodEnd": "2024-11-01",
      "cubicFeet": 1800,
      "cost": 191.28,
      "breakdown": {
        "water": 82.41,
        "sewer": 49.97,
        "sanitation": 33.81,
        "stormWater": 11.85,
        "streetLight": 4.59,
        "franchiseFee": 8.65
      }
    },
    {
      "month": "2024-11",
      "periodStart": "2024-11-02",
      "periodEnd": "2024-12-01",
      "cubicFeet": 400,
      "cost": 151.17,
      "breakdown": {
        "water": 47.05,
        "sewer": 49.04,
        "sanitation": 32.72,
        "stormWater": 11.46,
        "streetLight": 4.45,
        "franchiseFee": 6.45
      }
    },
    {
      "month": "2024-12",
      "periodStart": "2024-12-02",
      "periodEnd": "2025-01-01",
      "cubicFeet": 600,
      "cost": 158.87,
      "breakdown": {
        "water": 51.83,
        "sewer": 49.97,
        "sanitation": 33.81,
        "stormWater": 11.85,
        "streetLight": 4.59,
        "franchiseFee": 6.82
      }
    },
    {
      "month": "2025-01",
      "periodStart": "2025-01-02",
      "periodEnd": "2025-02-01",
      "cubicFeet": 500,
      "cost": 156.65,
      "breakdown": {
        "water": 49.74,
        "sewer": 49.97,
        "sanitation": 33.81,
        "stormWater": 11.85,
        "streetLight": 4.59,
        "franchiseFee": 6.69
      }
    },
    {
      "month": "2025-02",
      "periodStart": "2025-02-02",
      "periodEnd": "2025-03-01",
      "cubicFeet": 500,
      "cost": 146.85,
      "breakdown": {
        "water": 47.92,
        "sewer": 47.19,
        "sanitation": 30.54,
        "stormWater": 10.7,
        "streetLight": 4.15,
        "franchiseFee": 6.35
      }
    },
    {
      "month": "2025-03",
      "periodStart": "2025-03-02",
      "periodEnd": "2025-04-01",
      "cubicFeet": 500,
      "cost": 156.65,
      "breakdown": {
        "water": 49.74,
        "sewer": 49.97,
        "sanitation": 33.81,
        "stormWater": 11.85,
        "streetLight": 4.59,
        "franchiseFee": 6.69
      }
    },
    {
      "month": "2025-04",
      "periodStart": "2025-04-02",
      "periodEnd": "2025-05-01",
      "cubicFeet": 600,
      "cost": 155.6,
      "breakdown": {
        "water": 51.23,
        "sewer": 49.04,
        "sanitation": 32.72,
        "stormWater": 11.46,
        "streetLight": 4.45,
        "franchiseFee": 6.7
      }
    },
    {
      "month": "2025-05",
      "periodStart": "2025-05-02",
      "periodEnd": "2025-06-01",
      "cubicFeet": 3500,
      "cost": 248.3,
      "breakdown": {
        "water": 136.2,
        "sewer": 49.97,
        "sanitation": 33.81,
        "stormWater": 11.85,
        "streetLight": 4.59,
        "franchiseFee": 11.88
      }
    },
    {
      "month": "2025-06",
      "periodStart": "2025-06-02",
      "periodEnd": "2025-07-01",
      "cubicFeet": 7100,
      "cost": 400.97,
      "breakdown": {
        "water": 282.32,
        "sewer": 49.28,
        "sanitation": 32.83,
        "stormWater": 11.48,
        "streetLight": 4.47,
        "franchiseFee": 20.59
      }
    },
    {
      "month": "2025-07",
      "periodStart": "2025-07-02",
      "periodEnd": "2025-08-01",
      "cubicFeet": 6700,
      "cost": 451.46,
      "breakdown": {
        "water": 326.86,
        "sewer": 46.5,
        "sanitation": 37.19,
        "stormWater": 12.47,
        "streetLight": 5.29,
        "franchiseFee": 23.15
      }
    },
    {
      "month": "2025-08",
      "periodStart": "2025-08-02",
      "periodEnd": "2025-09-01",
      "cubicFeet": 6300,
      "cost": 430.6,
      "breakdown": {
        "water": 307.18,
        "sewer": 46.5,
        "sanitation": 37.19,
        "stormWater": 12.47,
        "streetLight": 5.29,
        "franchiseFee": 21.97
      }
    },
    {
      "month": "2025-09",
      "periodStart": "2025-09-02",
      "periodEnd": "2025-10-01",
      "cubicFeet": 4100,
      "cost": 314.07,
      "breakdown": {
        "water": 198.94,
        "sewer": 46.5,
        "sanitation": 35.99,
        "stormWater": 12.07,
        "streetLight": 5.12,
        "franchiseFee": 15.45
      }
    },
    {
      "month": "2025-10",
      "periodStart": "2025-10-02",
      "periodEnd": "2025-11-01",
      "cubicFeet": 900,
      "cost": 164.12,
      "breakdown": {
        "water": 56.73,
        "sewer": 46.5,
        "sanitation": 36.52,
        "stormWater": 12.25,
        "streetLight": 5.19,
        "franchiseFee": 6.93
      }
    },
    {
      "month": "2025-11",
      "periodStart": "2025-11-02",
      "periodEnd": "2025-12-01",
      "cubicFeet": 400,
      "cost": 146.31,
      "breakdown": {
        "water": 39.93,
        "sewer": 46.5,
        "sanitation": 36.52,
        "stormWater": 12.25,
        "streetLight": 5.19,
        "franchiseFee": 5.92
      }
    },
    {
      "month": "2025-12",
      "periodStart": "2025-12-02",
      "periodEnd": "2026-01-01",
      "cubicFeet": 500,
      "cost": 149.32,
      "breakdown": {
        "water": 42.77,
        "sewer": 46.5,
        "sanitation": 36.52,
        "stormWater": 12.25,
        "streetLight": 5.19,
        "franchiseFee": 6.09
      }
    },
    {
      "month": "2026-01",
      "periodStart": "2026-01-02",
      "periodEnd": "2026-02-01",
      "cubicFeet": 500,
      "cost": 149.32,
      "breakdown": {
        "water": 42.77,
        "sewer": 46.5,
        "sanitation": 36.52,
        "stormWater": 12.25,
        "streetLight": 5.19,
        "franchiseFee": 6.09
      }
    },
    {
      "month": "2026-02",
      "periodStart": "2026-02-02",
      "periodEnd": "2026-03-01",
      "cubicFeet": 500,
      "cost": 149.32,
      "breakdown": {
        "water": 42.77,
        "sewer": 46.5,
        "sanitation": 36.52,
        "stormWater": 12.25,
        "streetLight": 5.19,
        "franchiseFee": 6.09
      }
    },
    {
      "month": "2026-03",
      "periodStart": "2026-03-02",
      "periodEnd": "2026-04-01",
      "cubicFeet": 500,
      "cost": 149.32,
      "breakdown": {
        "water": 42.77,
        "sewer": 46.5,
        "sanitation": 36.52,
        "stormWater": 12.25,
        "streetLight": 5.19,
        "franchiseFee": 6.09
      }
    },
    {
      "month": "2026-04",
      "periodStart": "2026-04-02",
      "periodEnd": "2026-05-01",
      "cubicFeet": 400,
      "cost": 146.31,
      "breakdown": {
        "water": 39.93,
        "sewer": 46.5,
        "sanitation": 36.52,
        "stormWater": 12.25,
        "streetLight": 5.19,
        "franchiseFee": 5.92
      }
    },
    {
      "month": "2026-05",
      "periodStart": "2026-05-02",
      "periodEnd": "2026-06-01",
      "cubicFeet": 3000,
      "cost": 262.37,
      "breakdown": {
        "water": 149.42,
        "sewer": 46.5,
        "sanitation": 36.52,
        "stormWater": 12.25,
        "streetLight": 5.19,
        "franchiseFee": 12.49
      }
    },
    {
      "month": "2026-06",
      "periodStart": "2026-06-02",
      "periodEnd": "2026-07-01",
      "cubicFeet": 6300,
      "cost": 429.6,
      "breakdown": {
        "water": 307.18,
        "sewer": 46.5,
        "sanitation": 36.52,
        "stormWater": 12.25,
        "streetLight": 5.19,
        "franchiseFee": 21.96
      }
    }
  ],
  "electricityMonthly": [
    {
      "month": "2024-06",
      "kwh": 1571,
      "avgTempF": 70.85,
      "cost": 218
    },
    {
      "month": "2024-07",
      "kwh": 2433,
      "avgTempF": 83.14,
      "cost": 378
    },
    {
      "month": "2024-08",
      "kwh": 2295,
      "avgTempF": 82.85,
      "cost": 368
    },
    {
      "month": "2024-09",
      "kwh": 2007,
      "avgTempF": 73.55,
      "cost": 321
    },
    {
      "month": "2024-10",
      "kwh": 1645,
      "avgTempF": 68.29,
      "cost": 243
    },
    {
      "month": "2024-11",
      "kwh": 1089,
      "avgTempF": 45.45,
      "cost": 154
    },
    {
      "month": "2024-12",
      "kwh": 1276,
      "avgTempF": 37.83,
      "cost": 181
    },
    {
      "month": "2025-01",
      "kwh": 1351,
      "avgTempF": 34.16,
      "cost": 191
    },
    {
      "month": "2025-02",
      "kwh": 1231,
      "avgTempF": 36.57,
      "cost": 175
    },
    {
      "month": "2025-03",
      "kwh": 1186,
      "avgTempF": 43.39,
      "cost": 168
    },
    {
      "month": "2025-04",
      "kwh": 922,
      "avgTempF": 52.28,
      "cost": 130
    },
    {
      "month": "2025-05",
      "kwh": 1361,
      "avgTempF": 59.78,
      "cost": 200
    },
    {
      "month": "2025-06",
      "kwh": 1949,
      "avgTempF": 74.97,
      "cost": 311
    },
    {
      "month": "2025-07",
      "kwh": 2407,
      "avgTempF": 79.8,
      "cost": 403
    },
    {
      "month": "2025-08",
      "kwh": 2643,
      "avgTempF": 81.72,
      "cost": 448
    },
    {
      "month": "2025-09",
      "kwh": 2162,
      "avgTempF": 74.14,
      "cost": 366
    },
    {
      "month": "2025-10",
      "kwh": 1481,
      "avgTempF": 60.43,
      "cost": 230
    },
    {
      "month": "2025-11",
      "kwh": 1049,
      "avgTempF": 51.25,
      "cost": 158
    },
    {
      "month": "2025-12",
      "kwh": 1173,
      "avgTempF": 43.48,
      "cost": 176
    },
    {
      "month": "2026-01",
      "kwh": 1392,
      "avgTempF": 37.26,
      "cost": 209
    },
    {
      "month": "2026-02",
      "kwh": 1273,
      "avgTempF": 39.44,
      "cost": 191
    },
    {
      "month": "2026-03",
      "kwh": 1056,
      "avgTempF": 51.57,
      "cost": 158
    },
    {
      "month": "2026-04",
      "kwh": 908,
      "avgTempF": 55.05,
      "cost": 136
    },
    {
      "month": "2026-05",
      "kwh": 1565,
      "avgTempF": 58.34,
      "cost": 235
    },
    {
      "month": "2026-06",
      "kwh": 2275,
      "avgTempF": 72.02,
      "cost": 370
    }
  ],
  "electricityDaily": [
    {
      "date": "2026-06-13",
      "kwh": 72.98,
      "avgTempF": 72,
      "estCost": 12
    },
    {
      "date": "2026-06-14",
      "kwh": 76.08,
      "avgTempF": 73,
      "estCost": 12
    },
    {
      "date": "2026-06-15",
      "kwh": 73.28,
      "avgTempF": 73.5,
      "estCost": 12
    },
    {
      "date": "2026-06-16",
      "kwh": 83.51,
      "avgTempF": 78.5,
      "estCost": 14
    },
    {
      "date": "2026-06-17",
      "kwh": 94.1,
      "avgTempF": 79,
      "estCost": 15
    },
    {
      "date": "2026-06-18",
      "kwh": 80.45,
      "avgTempF": 75,
      "estCost": 13
    },
    {
      "date": "2026-06-19",
      "kwh": 100.28,
      "avgTempF": 79.5,
      "estCost": 16
    },
    {
      "date": "2026-06-20",
      "kwh": 99.56,
      "avgTempF": 78.5,
      "estCost": 16
    },
    {
      "date": "2026-06-21",
      "kwh": 68.29,
      "avgTempF": 74.5,
      "estCost": 11
    },
    {
      "date": "2026-06-22",
      "kwh": 68.09,
      "avgTempF": 78.5,
      "estCost": 11
    },
    {
      "date": "2026-06-23",
      "kwh": 71.83,
      "avgTempF": 83,
      "estCost": 12
    },
    {
      "date": "2026-06-24",
      "kwh": 73.11,
      "avgTempF": 84.5,
      "estCost": 12
    },
    {
      "date": "2026-06-25",
      "kwh": 61.68,
      "avgTempF": 78,
      "estCost": 11
    },
    {
      "date": "2026-06-26",
      "kwh": 63.32,
      "avgTempF": 84.5,
      "estCost": 11
    },
    {
      "date": "2026-06-27",
      "kwh": 50.05,
      "avgTempF": 67,
      "estCost": 9
    },
    {
      "date": "2026-06-28",
      "kwh": 41.13,
      "avgTempF": 62,
      "estCost": 8
    },
    {
      "date": "2026-06-29",
      "kwh": 40.31,
      "avgTempF": 59.5,
      "estCost": 8
    },
    {
      "date": "2026-06-30",
      "kwh": 43.23,
      "avgTempF": 68,
      "estCost": 8
    },
    {
      "date": "2026-07-01",
      "kwh": 67.61,
      "avgTempF": 77,
      "estCost": 11
    },
    {
      "date": "2026-07-02",
      "kwh": 57.62,
      "avgTempF": 75.5,
      "estCost": 10
    },
    {
      "date": "2026-07-03",
      "kwh": 65.69,
      "avgTempF": 79,
      "estCost": 11
    },
    {
      "date": "2026-07-04",
      "kwh": 71.53,
      "avgTempF": 80,
      "estCost": 12
    },
    {
      "date": "2026-07-05",
      "kwh": 88.63,
      "avgTempF": 85,
      "estCost": 14
    },
    {
      "date": "2026-07-06",
      "kwh": 106.02,
      "avgTempF": 88,
      "estCost": 15
    },
    {
      "date": "2026-07-07",
      "kwh": 92.36,
      "avgTempF": 82.5,
      "estCost": 14
    },
    {
      "date": "2026-07-08",
      "kwh": 112.21,
      "avgTempF": 85,
      "estCost": 16
    },
    {
      "date": "2026-07-09",
      "kwh": 105.74,
      "avgTempF": 84,
      "estCost": 15
    },
    {
      "date": "2026-07-10",
      "kwh": 104.92,
      "avgTempF": 85,
      "estCost": 15
    },
    {
      "date": "2026-07-11",
      "kwh": 113.85,
      "avgTempF": 88.5,
      "estCost": 16
    },
    {
      "date": "2026-07-12",
      "kwh": 138.6,
      "avgTempF": 93.5,
      "estCost": 19
    }
  ],
  "gas": [
    {
      "month": "2023-07",
      "periodStart": null,
      "periodEnd": "2023-08-09",
      "dth": 1.86,
      "dthWeatherAdj": 1.86,
      "cost": 31.93
    },
    {
      "month": "2023-08",
      "periodStart": "2023-08-10",
      "periodEnd": "2023-09-13",
      "dth": 17.51,
      "dthWeatherAdj": 17.6,
      "cost": 238
    },
    {
      "month": "2023-09",
      "periodStart": "2023-09-14",
      "periodEnd": "2023-10-11",
      "dth": 20.03,
      "dthWeatherAdj": 20.47,
      "cost": 272.18
    },
    {
      "month": "2023-10",
      "periodStart": "2023-10-12",
      "periodEnd": "2023-11-09",
      "dth": 5.7,
      "dthWeatherAdj": 6.25,
      "cost": 86.55
    },
    {
      "month": "2023-11",
      "periodStart": "2023-11-10",
      "periodEnd": "2023-12-11",
      "dth": 16.55,
      "dthWeatherAdj": 17.37,
      "cost": 249.56
    },
    {
      "month": "2023-12",
      "periodStart": "2023-12-12",
      "periodEnd": "2024-01-11",
      "dth": 22.08,
      "dthWeatherAdj": 22.83,
      "cost": 326.4
    },
    {
      "month": "2024-01",
      "periodStart": "2024-01-12",
      "periodEnd": "2024-02-12",
      "dth": 22.07,
      "dthWeatherAdj": 22.97,
      "cost": 320.59
    },
    {
      "month": "2024-02",
      "periodStart": "2024-02-13",
      "periodEnd": "2024-03-11",
      "dth": 17.15,
      "dthWeatherAdj": 17.49,
      "cost": 247.86
    },
    {
      "month": "2024-03",
      "periodStart": "2024-03-12",
      "periodEnd": "2024-04-09",
      "dth": 14.56,
      "dthWeatherAdj": 14.56,
      "cost": 205.45
    },
    {
      "month": "2024-04",
      "periodStart": "2024-04-10",
      "periodEnd": "2024-05-09",
      "dth": 9.6,
      "dthWeatherAdj": 10.15,
      "cost": 132.39
    },
    {
      "month": "2024-05",
      "periodStart": "2024-05-10",
      "periodEnd": "2024-06-11",
      "dth": 22.83,
      "dthWeatherAdj": 23.56,
      "cost": 302.8
    },
    {
      "month": "2024-06",
      "periodStart": "2024-06-12",
      "periodEnd": "2024-07-10",
      "dth": 8.98,
      "dthWeatherAdj": 9,
      "cost": 109.26
    },
    {
      "month": "2024-07",
      "periodStart": "2024-07-11",
      "periodEnd": "2024-08-09",
      "dth": 2.11,
      "dthWeatherAdj": 2.11,
      "cost": 25.34
    },
    {
      "month": "2024-08",
      "periodStart": "2024-08-10",
      "periodEnd": "2024-09-11",
      "dth": 15.99,
      "dthWeatherAdj": 16.04,
      "cost": 142.72
    },
    {
      "month": "2024-09",
      "periodStart": "2024-09-12",
      "periodEnd": "2024-10-10",
      "dth": 17.18,
      "dthWeatherAdj": 18.42,
      "cost": 156.26
    },
    {
      "month": "2024-10",
      "periodStart": "2024-10-11",
      "periodEnd": "2024-11-12",
      "dth": 8.11,
      "dthWeatherAdj": 8.71,
      "cost": 80.54
    },
    {
      "month": "2024-11",
      "periodStart": "2024-11-13",
      "periodEnd": "2024-12-10",
      "dth": 15.11,
      "dthWeatherAdj": 15.48,
      "cost": 149.94
    },
    {
      "month": "2024-12",
      "periodStart": "2024-12-11",
      "periodEnd": "2025-01-10",
      "dth": 19.97,
      "dthWeatherAdj": 24.28,
      "cost": 210.76
    },
    {
      "month": "2025-01",
      "periodStart": "2025-01-11",
      "periodEnd": "2025-02-10",
      "dth": 23.25,
      "dthWeatherAdj": 24.3,
      "cost": 229.4
    },
    {
      "month": "2025-02",
      "periodStart": "2025-02-11",
      "periodEnd": "2025-03-11",
      "dth": 17.99,
      "dthWeatherAdj": 18.54,
      "cost": 176.57
    },
    {
      "month": "2025-03",
      "periodStart": "2025-03-12",
      "periodEnd": "2025-04-08",
      "dth": 11.98,
      "dthWeatherAdj": 11.83,
      "cost": 114.24
    },
    {
      "month": "2025-04",
      "periodStart": "2025-04-09",
      "periodEnd": "2025-05-08",
      "dth": 6.28,
      "dthWeatherAdj": 8.81,
      "cost": 66.81
    },
    {
      "month": "2025-05",
      "periodStart": "2025-05-09",
      "periodEnd": "2025-06-09",
      "dth": 36.14,
      "dthWeatherAdj": 37.16,
      "cost": 305.3
    },
    {
      "month": "2025-06",
      "periodStart": "2025-06-10",
      "periodEnd": "2025-07-10",
      "dth": 1.89,
      "dthWeatherAdj": 1.89,
      "cost": 22.89
    },
    {
      "month": "2025-07",
      "periodStart": "2025-07-11",
      "periodEnd": "2025-08-12",
      "dth": 2.56,
      "dthWeatherAdj": 2.56,
      "cost": 28.44
    },
    {
      "month": "2025-08",
      "periodStart": "2025-08-13",
      "periodEnd": "2025-09-09",
      "dth": 1.79,
      "dthWeatherAdj": 1.85,
      "cost": 22.35
    },
    {
      "month": "2025-09",
      "periodStart": "2025-09-10",
      "periodEnd": "2025-10-07",
      "dth": 18.83,
      "dthWeatherAdj": 19.9,
      "cost": 166.06
    },
    {
      "month": "2025-10",
      "periodStart": "2025-10-08",
      "periodEnd": "2025-11-07",
      "dth": 4.88,
      "dthWeatherAdj": 5.42,
      "cost": 52.06
    },
    {
      "month": "2025-11",
      "periodStart": "2025-11-08",
      "periodEnd": "2025-12-05",
      "dth": 9.11,
      "dthWeatherAdj": 11.36,
      "cost": 105.22
    },
    {
      "month": "2025-12",
      "periodStart": "2025-12-06",
      "periodEnd": "2026-01-08",
      "dth": 14.57,
      "dthWeatherAdj": 23.71,
      "cost": 189.63
    },
    {
      "month": "2026-01",
      "periodStart": "2026-01-09",
      "periodEnd": "2026-02-06",
      "dth": 16.31,
      "dthWeatherAdj": 17.23,
      "cost": 179.29
    },
    {
      "month": "2026-02",
      "periodStart": "2026-02-07",
      "periodEnd": "2026-03-10",
      "dth": 13.89,
      "dthWeatherAdj": 16.37,
      "cost": 161.63
    },
    {
      "month": "2026-03",
      "periodStart": "2026-03-11",
      "periodEnd": "2026-04-10",
      "dth": 6.34,
      "dthWeatherAdj": 10.25,
      "cost": 86.95
    },
    {
      "month": "2026-04",
      "periodStart": "2026-04-11",
      "periodEnd": "2026-05-11",
      "dth": 6.97,
      "dthWeatherAdj": 7.47,
      "cost": 71.56
    },
    {
      "month": "2026-05",
      "periodStart": "2026-05-12",
      "periodEnd": "2026-06-09",
      "dth": 17.79,
      "dthWeatherAdj": 18.39,
      "cost": 169.62
    },
    {
      "month": "2026-06",
      "periodStart": "2026-06-10",
      "periodEnd": "2026-07-10",
      "dth": 2.45,
      "dthWeatherAdj": 2.5,
      "cost": 30.04
    }
  ]
};
